/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package constants.programs;

import client.MapleCharacter;
import client.MapleClient;
import constants.ServerConstants;
import database.MYSQL;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.concurrent.ScheduledFuture;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import launch.ChannelServer;
import launch.LoginServer;
import launch.Start;
import launch.world.WorldBroadcasting;
import launch.world.WorldCommunity;
import packet.creators.MainPacketCreator;
import packet.creators.UIPacket;
import server.maps.MapleMap;
import tools.Timer;
import tools.Timer.WorldTimer;

/**
 *
 * @author Administrator
 */
public class ControlUnit extends javax.swing.JFrame {

    public ControlUnit() {
     	Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((screenSize.width - 1505) / 2, (screenSize.height - 576) / 2); 
        initComponents();
        서버정보불러오기();
        환율정보();
        채팅금지();
        벤();
        this.setTitle("Control Panel");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jjj = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        drop = new javax.swing.JTextField();
        meso = new javax.swing.JTextField();
        exp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        serverMessage = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Chat = new javax.swing.JList();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        mesos = new javax.swing.JLabel();
        realcash = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        chatban = new javax.swing.JList();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ban = new javax.swing.JList();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        동시접속자 = new javax.swing.JList();
        jLabel18 = new javax.swing.JLabel();
        접속자수 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        noticMessage = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        hottime = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(527, 300));

        jPanel1.setLayout(null);

        jLabel8.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel8.setText("<Server information Settings>");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(28, 40, 200, 15);

        jLabel9.setForeground(new java.awt.Color(51, 0, 255));
        jLabel9.setText("EXP");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 80, 48, 14);

        jjj.setForeground(new java.awt.Color(255, 51, 51));
        jjj.setText("MESO");
        jPanel1.add(jjj);
        jjj.setBounds(160, 80, 40, 14);

        jLabel10.setForeground(new java.awt.Color(51, 0, 153));
        jLabel10.setText("DROP");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(270, 80, 40, 14);

        drop.setText("Drop");
        jPanel1.add(drop);
        drop.setBounds(270, 101, 100, 50);

        meso.setText("Meso");
        jPanel1.add(meso);
        meso.setBounds(158, 101, 100, 50);

        exp.setText("Exp");
        jPanel1.add(exp);
        exp.setBounds(30, 101, 120, 50);

        jLabel11.setText("Server Message (server message at the top)");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 160, 270, 20);

        serverMessage.setText("Server top message");
        serverMessage.setToolTipText("");
        serverMessage.setMaximumSize(new java.awt.Dimension(6, 21));
        serverMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverMessageActionPerformed(evt);
            }
        });
        jPanel1.add(serverMessage);
        serverMessage.setBounds(30, 190, 460, 170);

        jButton14.setForeground(new java.awt.Color(153, 153, 153));
        jButton14.setText("Change the Server Information");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(30, 380, 460, 170);

        jTabbedPane1.addTab("Server Settings", jPanel1);

        jButton1.setText("Sponsorship payments");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("nickname");

        jTextField2.setText("Point");

        jLabel1.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel1.setText("<Sponsorship>");

        jLabel2.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel2.setText("<GM Settings>");

        jTextField3.setText("nickname");

        jButton2.setText("GM settings");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel3.setText("<Item Payments>");

        jTextField4.setText("nickname");

        jButton3.setText("Items paid");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField5.setText("Item code, number");

        jLabel4.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel4.setText("<Payment mesos>");

        jTextField6.setText("nickname");

        jTextField7.setText("Mesos");

        jButton4.setText("Payment methods");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel5.setText("<User Ban>");

        jTextField8.setText("nickname (off the account)");

        jTextField9.setText("Reason");

        jButton5.setText("Ban");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel6.setText("<Chat prohibited>");

        jTextField10.setText("nickname");

        jButton6.setText("Ban chat");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Chat prohibit release");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel7.setText("<Early group chat>");

        jButton8.setText("Early group chat");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton19.setText("Desban");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jButton5)
                                        .addGap(40, 40, 40)
                                        .addComponent(jButton19))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(6, 6, 6)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(6, 6, 6)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(20, 20, 20)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jButton8))
                .addGap(41, 41, 41))
        );

        jTabbedPane1.addTab("Server Features 2", jPanel3);

        Chat.setForeground(new java.awt.Color(102, 0, 102));
        Chat.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(Chat);

        jLabel16.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 102));
        jLabel16.setText("<Real-time chat logs>");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jLabel16)
                .addContainerGap(298, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Chat Logs", jPanel4);

        mesos.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
        mesos.setForeground(new java.awt.Color(204, 0, 204));
        mesos.setText("Total server mesos :");

        realcash.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
        realcash.setForeground(new java.awt.Color(0, 153, 102));
        realcash.setText("The total sponsorship server points :");

        jLabel19.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel19.setText("<Server mesos total (excluding GM), the server hupo total (excluding GM)>");

        jLabel20.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel20.setText("[All records will be displayed in the last reboot standards.]");

        jLabel21.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 51));
        jLabel21.setText("<Chatting with banned party>");

        chatban.setForeground(new java.awt.Color(255, 0, 51));
        chatban.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatbanMouseClicked(evt);
            }
        });
        chatban.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                chatbanComponentShown(evt);
            }
        });
        chatban.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                chatbanFocusGained(evt);
            }
        });
        jScrollPane2.setViewportView(chatban);

        jLabel22.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 204));
        jLabel22.setText("<Account Ban>");

        ban.setForeground(new java.awt.Color(51, 0, 204));
        ban.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                banMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ban);

        jLabel17.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 102, 0));
        jLabel17.setText("<Current user connections>");

        동시접속자.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                동시접속자MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(동시접속자);

        jLabel18.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel18.setText("Number of users:");

        접속자수.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        접속자수.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(92, 92, 92)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22)))
                            .addComponent(realcash, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mesos, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(124, 124, 124))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(접속자수)
                                .addGap(47, 47, 47)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(16, 16, 16))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(접속자수)
                            .addComponent(jLabel18)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(mesos)
                        .addGap(5, 5, 5)
                        .addComponent(realcash)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Server Status", jPanel5);

        jLabel12.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel12.setText("<Notice> Send");

        noticMessage.setText("Notice");
        noticMessage.setMaximumSize(new java.awt.Dimension(6, 21));
        noticMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noticMessageActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 204, 51));
        jButton11.setText("Show Info");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton9.setForeground(new java.awt.Color(0, 51, 204));
        jButton9.setText("pop-up");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setForeground(new java.awt.Color(255, 0, 204));
        jButton10.setText("pink");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        hottime.setText("Item code, number");

        jLabel13.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel13.setText("<Hot Time>");

        jButton12.setForeground(new java.awt.Color(153, 0, 204));
        jButton12.setText("NPC");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton18.setText("Both go to the Star Planet");
        jButton18.setToolTipText("");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton17.setText("Server shutdown");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel14.setText("<Server-related>");

        jButton13.setText("Hot-time payments");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton16.setText("Both go to the login server");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton15.setText("Save All");
        jButton15.setToolTipText("");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hottime)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(noticMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 283, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(noticMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hottime, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton15)
                .addGap(18, 18, 18)
                .addComponent(jButton16)
                .addGap(33, 33, 33)
                .addComponent(jButton17)
                .addGap(26, 26, 26)
                .addComponent(jButton18)
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Server Features", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void 환율정보() {
        long meso = 0;
        int realcash = 0;
        try {
            ResultSet ps = MYSQL.getConnection().prepareStatement("SELECT * FROM characters WHERE gm = 0").executeQuery();
            while (ps.next()) {
                meso += ps.getLong("meso");
            }
            ps.close();
            ps = MYSQL.getConnection().prepareStatement("SELECT * FROM storages").executeQuery();
            while (ps.next()) {
                meso += ps.getLong("meso");
            }
            mesos.setText(mesos.getText() + meso + "$");
            ps = MYSQL.getConnection().prepareStatement("SELECT * FROM accounts WHERE gm = 0").executeQuery();
            while (ps.next()) {
                realcash += ps.getInt("realcash");
            }
            ps.close();
            this.realcash.setText(this.realcash.getText() + realcash + "$");
        } catch (SQLException ex) {

        }
    }
    
    public void 벤() {
        try {
          ResultSet ps = MYSQL.getConnection().prepareStatement("SELECT * FROM accounts WHERE gm = 0").executeQuery();
          while (ps.next()) {
              if (ps.getInt("banned") != 0) {
                  BanList.addElement(ps.getString("name"));
              } 
          }
          ps.close();
          ban.setModel(BanList);
        } catch (SQLException ex) {
            
        }      
    } 
    
    public void 채팅금지() {
        String name = "";
        try {
            ResultSet rs = MYSQL.getConnection().prepareStatement("SELECT * FROM characters WHERE gm = 0").executeQuery();
            while (rs.next()) {
                if (rs.getString("chatban").equals("true")) {
                    ChatbanList.addElement(rs.getString("name"));
                }
            }
            rs.close();
            chatban.setModel(ChatbanList);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            boolean check = false;
            for (ChannelServer cs : ChannelServer.getAllInstances()) {
                MapleCharacter hp = null;
                hp = cs.getPlayerStorage().getCharacterByName(this.jTextField1.getText());
                if (hp == null && !check) {
                    check = false;
                } else if (hp != null) {
                    check = true;
                    hp.gainRC(Integer.parseInt(this.jTextField2.getText()));            
                    hp.dropMessage(5, "From server [" + Integer.parseInt(this.jTextField2.getText()) + "] He received a sponsorship point paid.");
                    JOptionPane.showMessageDialog(null, jTextField1.getText() + "To have a sponsor's payment points.");
                    초기화();
                    return;
               }
            }
            if (!check) {
                JOptionPane.showMessageDialog(null, "Not being connected to the player.");
            }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            boolean check = false;
            for (ChannelServer cs : ChannelServer.getAllInstances()) {
                MapleCharacter hp = null;
                hp = cs.getPlayerStorage().getCharacterByName(this.jTextField3.getText());
                if (hp == null && !check) {
                    check = false;
                } else if (hp != null) {
                    check = true;
                    hp.setGMLevel((byte) 6);
                    hp.dropShowInfo("GM has been set.");
                    JOptionPane.showMessageDialog(null, "GM has been the setting.");
                    초기화();
                    return;
               }
            }
            if (!check) {
                JOptionPane.showMessageDialog(null, "Not being connected to the player.");
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            boolean check = false;
            for (ChannelServer cs : ChannelServer.getAllInstances()) {
                MapleCharacter hp = null;
                hp = cs.getPlayerStorage().getCharacterByName(this.jTextField4.getText());
                if (hp == null && !check) {
                    check = false;
                } else if (hp != null) {
                    check = true;
                    String a[] = this.jTextField5.getText().split(",");
                    int itemid = Integer.parseInt(a[0]);
                    short quantity = Short.parseShort(a[1]);
                    hp.gainItem(itemid, quantity, false, -1, null);
                    hp.dropMessage(1, "He received a payment item.");
                    JOptionPane.showMessageDialog(null, "The item was paid.");
                    초기화();
                    return;
               }
            }
            if (!check) {
                JOptionPane.showMessageDialog(null, "Not being connected to the player.");
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            boolean check = false;
            for (ChannelServer cs : ChannelServer.getAllInstances()) {
                MapleCharacter hp = null;
                hp = cs.getPlayerStorage().getCharacterByName(this.jTextField6.getText());
                if (hp == null && !check) {
                    check = false;
                } else if (hp != null) {
                    check = true;
                    hp.gainMeso(Long.parseLong(this.jTextField7.getText()), true);
                    hp.dropMessage(1, "He received a payment method.");
                    JOptionPane.showMessageDialog(null, "The method has been paid.");
                    초기화();
                    return;
               }
            }
            if (!check) {
                JOptionPane.showMessageDialog(null, "Not being connected to the player.");
            }
    }//GEN-LAST:event_jButton4ActionPerformed

   public static void 서버정보불러오기() {
        for (ChannelServer cserv : ChannelServer.getAllInstances()) {
            exp.setText(cserv.getExpRate() + "");
            drop.setText(cserv.getDropRate() + "");
            meso.setText(cserv.getMesoRate() + "");
            serverMessage.setText(cserv.getServerMessage());
            break;
        }
   }    
   
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            boolean check = false;
            for (ChannelServer cs : ChannelServer.getAllInstances()) {
                MapleCharacter hp = null;
                hp = cs.getPlayerStorage().getCharacterByName(this.jTextField8.getText());
                if (hp == null && !check) {
                    check = false;
                } else if (hp != null) {
                    final MapleClient c = null;
                    check = true;
                    hp.ban(jTextField8.getText(), true, false);
                    c.getSession().write(MainPacketCreator.getNPCTalk(2007, (byte) 0, "This account can not be used from now on.\r\n(Automatically terminated after 3 seconds).", "00 00", (byte) 2));
                    BanList.addElement(hp.getClient().getAccountName());
                    ban.setModel(BanList);
                    Timer.EtcTimer tMan = Timer.EtcTimer.getInstance();
                    tMan.schedule(new Runnable() {
                    @Override
                    public void run() {
                        c.disconnect(true, (c.getLoginState() == 4 || c.getLoginState() == 5));
                        c.getSession().close();
                        c.getSession().close();
                      }
                    }, 3000);
                    JOptionPane.showMessageDialog(null, jTextField8.getText() + "Ban was a user.");
                    초기화();
                    return;
               }
            }
            if (!check) {
                JOptionPane.showMessageDialog(null, "Not being connected to the player.");
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            boolean check = false;
            for (ChannelServer cs : ChannelServer.getAllInstances()) {
                MapleCharacter hp = null;
                hp = cs.getPlayerStorage().getCharacterByName(this.jTextField10.getText());
                if (hp == null && !check) {
                    check = false;
                } else if (hp != null) {
                    check = true;
                    hp.setChatban("true");
                    hp.dropMessage(1, "Per has a chat ban.");
                    JOptionPane.showMessageDialog(null, "Have a chat ban.");
                    ChatbanList.addElement(hp.getName());
                    chatban.setModel(ChatbanList);
                    초기화();
                    return;
               }
            }
            if (!check) {
                JOptionPane.showMessageDialog(null, "Not being connected to the player.");
            }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
            boolean check = false;
            for (ChannelServer cs : ChannelServer.getAllInstances()) {
                MapleCharacter hp = null;
                hp = cs.getPlayerStorage().getCharacterByName(this.jTextField10.getText());
                if (hp == null && !check) {
                    check = false;
                } else if (hp != null) {
                    check = true;
                    hp.setChatban("false");
                    hp.dropMessage(1, "Chat ban has been lifted.");
                    JOptionPane.showMessageDialog(null, "I have disabled the chat prohibited.");
                    ChatList.removeElement(jTextField10.getText());
                    chatban.setModel(ChatList);
                    초기화();
                    return;
               }
            }
            if (!check) {
                JOptionPane.showMessageDialog(null, "Not being connected to the player.");
            }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       if (!WorldCommunity.얼리기) {
        WorldCommunity.얼리기 = true;
        this.jButton8.setText("채팅 녹이기");
        WorldBroadcasting.broadcastMessage(MainPacketCreator.serverNotice(1, "The chat was frozen."));
        JOptionPane.showMessageDialog(null, "And it gave Earl a chat.");
       } else {
           WorldCommunity.얼리기  = false;
           this.jButton8.setText("채팅 얼리기");
           WorldBroadcasting.broadcastMessage(MainPacketCreator.serverNotice(1, "This chat has melted."));
           JOptionPane.showMessageDialog(null, "Rust was chatting.");
       }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        String b[] = this.hottime.getText().split(",");
        int itemid = Integer.parseInt(b[0]);
        short quantity = Short.parseShort(b[1]);
        for (ChannelServer cs : ChannelServer.getAllInstances()) {
            for (MapleCharacter chr : cs.getPlayerStorage().getAllCharacters().values()) {
                chr.gainItem(itemid, quantity, false, -1, null);
            }
        }
        WorldBroadcasting.broadcastMessage(MainPacketCreator.serverNotice(1, "Hot-time items was paid."));
        JOptionPane.showMessageDialog(null, "Hot-time items was paid.");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        for (int i = 0; i <= ServerConstants.serverCount; i ++) {
        ChannelServer.getInstance(i).setExpRate(Integer.parseInt(this.exp.getText()));
        ChannelServer.getInstance(i).setMesoRate((byte)Integer.parseInt(this.meso.getText()));
        ChannelServer.getInstance(i).setDropRate(Integer.parseInt(this.drop.getText()));
        ChannelServer.getInstance(i).setServerMessage(this.serverMessage.getText());
       }
       JOptionPane.showMessageDialog(null, "It changed the server information.");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        공지사항(1,this.noticMessage.getText());
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        공지사항(5,this.noticMessage.getText());
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        공지사항(-1,this.noticMessage.getText());
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        공지사항(-2,this.noticMessage.getText());
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        for (ChannelServer cs : ChannelServer.getAllInstances()) {
            for (MapleCharacter chr : cs.getPlayerStorage().getAllCharacters().values()) {
                chr.saveToDB(false,false);
            }
        }
        JOptionPane.showMessageDialog(null, "Both have completed the save.");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
                for (ChannelServer cserv : ChannelServer.getAllInstances()) {
                    cserv.getPlayerStorage().disconnectAll();
                } 
                JOptionPane.showMessageDialog(null, "All players have been moved to the login server.");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

        for (ChannelServer cs : ChannelServer.getAllInstances()) {
            cs.closeAllMerchant();
            cs.saveAllMerchant();
            cs.getPlayerStorage().disconnectAll();
          //  LoginServer.getInstance().shutdown();
        }
        JOptionPane.showMessageDialog(null, "I shut down the server.");
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        MapleMap map = null;
        for (ChannelServer cs : ChannelServer.getAllInstances()) {
            for (MapleCharacter hp : cs.getPlayerStorage().getAllCharacters().values()) {
                hp.warp(340000100);
            }
        }
        JOptionPane.showMessageDialog(null, "Every player has moved the planet into a star.");
    }//GEN-LAST:event_jButton18ActionPerformed

    private void chatbanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatbanMouseClicked
       
    }//GEN-LAST:event_chatbanMouseClicked

    private void chatbanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chatbanFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_chatbanFocusGained

    private void chatbanComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_chatbanComponentShown
       // JOptionPane.showMessageDialog(null,chatban.getDropTarget().toString());
    }//GEN-LAST:event_chatbanComponentShown

    private void 동시접속자MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_동시접속자MouseClicked
        try {
            if (동시접속자.getModel() != null) {
                String name = 동시접속자.getModel().getElementAt(동시접속자.getSelectedIndex()).toString();
                jTextField1.setText(name);
                jTextField3.setText(name);
                jTextField4.setText(name);
                jTextField6.setText(name);
                jTextField8.setText(name);
                jTextField10.setText(name);
            }
        } catch (Exception e) {
           
        }
    }//GEN-LAST:event_동시접속자MouseClicked

    private void banMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banMouseClicked
      try {
        jTextField8.setText(ban.getModel().getElementAt(ban.getSelectedIndex()).toString());
      } catch(Exception e) {
          
      }
    }//GEN-LAST:event_banMouseClicked

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
            try {
                Connection con = MYSQL.getConnection();
                PreparedStatement ps = con.prepareStatement("UPDATE accounts SET banned = ?, banreason = ? WHERE name = ?");
                ps.setInt(1, 0);
                ps.setString(2, "");
                ps.setString(3, jTextField8.getText());
                ps.executeUpdate();
                ps.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            BanList.removeElement(jTextField8.getText());
            ban.setModel(BanList);
            JOptionPane.showMessageDialog(null, jTextField8.getText() + "It has released the game's blackout.");
            초기화();
    }//GEN-LAST:event_jButton19ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void serverMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serverMessageActionPerformed

    private void noticMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noticMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noticMessageActionPerformed

    
     public String 아이피(String name) throws SQLException {
         String a = "";
         PreparedStatement ps2 = MYSQL.getConnection().prepareStatement("SELECT * FROM accounts WHERE name = ?");
         ps2.setString(1, name);
         ResultSet con = ps2.executeQuery();
         while(con.next()) {
             a = con.getString("ip");
         }
         ps2.close();
         con.close();
         return a;
    }
    
    public void 초기화() {
        String name = "닉네임";
            jTextField1.setText(name);
            jTextField3.setText(name);
            jTextField4.setText(name);
            jTextField6.setText(name);
            jTextField8.setText("닉네임(해제는 계정)");
            jTextField10.setText(name);  
    }
    
    public void 공지사항(int i, String text) {
        if (i == -1) {
            WorldBroadcasting.broadcastMessage(UIPacket.showInfo(text));
        } else if (i == -2) {
            WorldBroadcasting.broadcastMessage(MainPacketCreator.getNPCTalk(2007, (byte) 0, text, "00 00", (byte) 0));
        } else {
            WorldBroadcasting.broadcastMessage(MainPacketCreator.serverNotice(i,text));
        }
        JOptionPane.showMessageDialog(null, "[" + text + "] The information notified to all players.");
    }
    
    public static void 동접(String a) {
        try {
            현재접속자.addElement(a);
            동시접속자.setModel(현재접속자);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public static void 동접제거(String a) {
        현재접속자.removeElement(a);
        동시접속자.setModel(현재접속자);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlUnit().setVisible(true);
            }
        });
    }
    
    public static DefaultListModel ChatList = new DefaultListModel();
    public static DefaultListModel 현재접속자 = new DefaultListModel();
    private DefaultListModel ChatbanList = new DefaultListModel();
    private DefaultListModel BanList = new DefaultListModel();
    private transient ScheduledFuture<?> chattime;
    private int timeo = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JList Chat;
    private javax.swing.JList ban;
    private javax.swing.JList chatban;
    private static javax.swing.JTextField drop;
    private static javax.swing.JTextField exp;
    private javax.swing.JTextField hottime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel jjj;
    private static javax.swing.JTextField meso;
    private javax.swing.JLabel mesos;
    private javax.swing.JTextField noticMessage;
    private javax.swing.JLabel realcash;
    private static javax.swing.JTextField serverMessage;
    public static javax.swing.JList 동시접속자;
    public static javax.swing.JLabel 접속자수;
    // End of variables declaration//GEN-END:variables
}
